times = ('São Paulo', 'Coritiba', 'Corinthians', 'Atlético-MG', 'Ceará', 'Avaí', 'Cuiabá', 'Flamengo', 'Atlético-GO', 'Santos', 'Fluminense', 'Bragantino', 'Juventude', 'Palmeiras', 'Fortaleza', 'América-MG', 'Botafogo', 'Internacional', 'Goiás', 'Athletico-PR')
print('-=' * 20)
print(f'Lista de times do brasileirão: {times}')
print('-=' * 20)
print(f'Os cinco primeiros colocados são{times[:5]}')
print('-=' * 20)
print(f'Os 4 ultimos colocados são{times[-4:]}')
print('-=' * 20)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 20)
print('O Flamengo está na {}° posição'.format(times.index('Flamengo')+1))